#!/usr/bin/python3
# -*- coding: utf-8 -*-
# key-mapper - GUI for device specific keyboard mappings
# Copyright (C) 2021 sezanzeb <proxima@sezanzeb.de>
#
# This file is part of key-mapper.
#
# key-mapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# key-mapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with key-mapper.  If not, see <https://www.gnu.org/licenses/>.


"""A set of all human readable symbols xkb understands."""

# https://gist.github.com/sezanzeb/1236917f509f13d30010c98c9fa8389f
VALID_XKB_SYMBOLS = {
    'xf86mailforward', 'pointer_enablekeys', 'xf86sleep', 'hebrew_aleph',
    'asterisk', 'utilde', 'armenian_ben', 'arabic_feh', 'armenian_nu', 'colon',
    'kp_7', 'farsi_7', 'minutes', 'armenian_at', 'xf86launch6', 'kp_left',
    'arabic_7', 'braille_dot_5', 'currency', 'xf86cut', 'muhenkan', 'sinh_ng',
    'abovedot', 'armenian_tche', 'arabic_3', 'henkan', 'ninesuperior',
    'xf86audiorecord', 'sinh_ru2', 'thai_phinthu', 'sinh_la', 'ellipsis',
    'dead_psili', 'dead_abovedot', 'kana_yo', 'thai_lu', 'shift_r', 'gcedilla',
    'mode_switch', 'kana_ki', 'xf86touchpadoff', 'thai_maitri', 'farsi_4',
    'xf86tools', 'arabic_hamza', 'redo', 'sunpaste', 'masculine', 'arabic_teh',
    'xf86user2kb', 'armenian_vyun', 'hfgsfghsfg', 'thai_ngongu', 'suncopy',
    'arabic_0', 'jot', 'kana_na', 'abreve', 'sinh_jnya', 'f21', 'georgian_en',
    'next', 'sterling', 'lcedilla', 'armenian_pe', 'grave', 'twosubscript',
    'ubreve', 'macedonia_dse', 'greek_delta', 'thai_honokhuk', 'caron',
    'cyrillic_o_bar', 'sinh_aee2', 'xf86next_vmode', 'question',
    'georgian_man', 'l4', 'xf86meeting', 'xf86send', 'xf86cleargrab',
    'xf86menupb', 'cyrillic_de', 'rcaron', 'backspace', 'l3',
    'xf86switch_vt_2', 'thai_leksun', 'prolongedsound', 'xf86launch4',
    'integral', 'alt_l', 'xf86rfkill', 'space', 'dead_horn', 'l', 'greek_mu',
    'odoubleacute', 'racute', 'xf86vendorhome', 'includes', 'ukrainian_i',
    'less', 'dead_currency', 'threequarters', 'kp_end', 'cyrillic_a',
    'armenian_hi', 'thai_lekchet', 'kana_he', 'georgian_on',
    'cyrillic_che_vertstroke', 'kana_te', 'dead_doubleacute', 'uacute',
    'guilsinglleft', 'braille_dot_6', 'cyrillic_che', 'cyrillic_te', 'f32',
    'ohorn', 'find', 'xf86lightbulb', 'sinh_e', 'dead_stroke', 'hpdeletechar',
    'cyrillic_yu', 'a', 'xf86hibernate', 'iso_last_group', 'nosymbol',
    'dead_abovering', 'xf86rotatewindows', 'cyrillic_shha', 'xf86splitscreen',
    'lowrightcorner', 'sinh_aa2', 'infinity', 'ediaeresis',
    'cyrillic_hardsign', 'iso_first_group', 'kana_ko', 'q', 'lessthanequal',
    'xf86rotationpb', 'ifonlyif', 'kana_i', 'kp_tab', 'arabic_6', '5',
    'nacute', 'armenian_je', 'braceleft', 'singlelowquotemark', 'aogonek',
    'cyrillic_o', 'dead_belowmacron', 'quotedbl', 'hebrew_yod', 'xf86launchb',
    'xf86switch_vt_8', 'sinh_mba', 'sinh_ndha', 'f13', 'greek_chi',
    'arabic_percent', 'xf86switch_vt_7', 'georgian_gan', 'xf86support',
    'hebrew_tet', 'armenian_vev', 'kp_f1', 'overbar', 'arabic_alef',
    'cyrillic_lje', 'sinh_pha', 'xf86launch1', 'dead_caron', 'xf86calculator',
    'semicolon', 'hangul_hanja', 'otilde', 'georgian_don', 'georgian_rae',
    'xf86clear', 'includedin', 'hebrew_gimel', 'iso_level3_shift',
    'georgian_jhan', 'approxeq', 'xf86launchd', 'sunvideolowerbrightness',
    'xf86launch9', 'bracketright', 'arabic_hamzaonalef', 'xf86market',
    'dead_grave', 'braille_dot_2', 'hebrew_nun', 'downarrow',
    'xf86kbdbrightnessdown', 'sinh_uu2', 'xf86copy', 'eightsuperior',
    'thai_leksam', 'xf86wwan', 'arabic_meem', 'eth', 'sinh_na', 'xf86pictures',
    'xf86audiostop', 'xf86reply', 'hebrew_finalkaph', 'thai_sosua',
    'thai_khokhai', 'arabic_beh', 'xf86prev_vmode', 'l8', 'hebrew_qoph',
    'xf86brightnessadjust', 'sinh_ssha', 'thai_phophan', 'armenian_hyphen',
    'kp_4', 'z', 'armenian_tso', 'sunfa_tilde', 'braille_dot_1', 'percent',
    '7', 'oslash', 'f', 'seveneighths', 'kana_re', 'sunsys_req', 'sinh_aa',
    'cyrillic_ha_descender', 'enopencircbullet', 'sinh_lla', 'georgian_an',
    'leftdoublequotemark', 'arabic_lam', 'xf86applicationright', 'sys_req',
    'ezh', 'xf86new', 'hebrew_samech', 'ibreve', 'thai_thothan', 'menu',
    'onesuperior', 'sunfa_circum', 'help', 'lstroke', 'iso_level5_shift',
    'sunaudioraisevolume', 'f25', 'crossinglines', 'f27', 'thai_sarauu', '4',
    'dongsign', 'kp_9', 'sixsuperior', 'xf86switch_vt_1', 'uprightcorner',
    'sunfa_grave', 'shift_l', 'thai_dodek', 'hebrew_shin', 'xf86logoff',
    'ccedilla', 'greek_upsilon', 'sunfa_cedilla', 'sinh_ka', 'clear',
    'greek_tau', 'farsi_2', 'sinh_e2', 'leftanglebracket', 'down',
    'xf86applicationleft', 'sinh_fa', 'sunundo', 'armenian_cha', 'kp_2', 'l7',
    'xf86finance', 'thai_choching', 'sunvideodegauss', 'sinh_ii', 'hebrew_he',
    'u', 'georgian_xan', 'g', 'equal', 'thai_khorakhang',
    'arabic_heh_doachashmee', 'georgian_tar', 'xf86display', 'hebrew_zade',
    'f10', 'meta_l', 'plusminus', 'v', 'e', 'l9', 'braille_dot_7', 'sinh_kha',
    'cyrillic_zhe_descender', 'sunfa_acute', 'greek_sigma', 'thai_nikhahit',
    'xf86excel', 'kp_5', 'xf86touchpadtoggle', 'armenian_pyur',
    'thai_saraaimaimalai', 'kp_add', 'cyrillic_pe', 'iso_prev_group',
    'udiaeresis', 'sinh_luu2', 'xf86community', 'f24', 'kana_o', 'scaron',
    'udoubleacute', 'arabic_semicolon', 'alt_r', 'armenian_question',
    'sinh_al', 'xf86switch_vt_11', 'dead_longsolidusoverlay', 'farsi_6',
    'plus', 'p', 'hiragana_katakana', 'ampersand', 'georgian_phar', 'cent',
    'xf86spell', 'zabovedot', '1', 'rightsinglequotemark', 'arabic_sad', '8',
    'arabic_kaf', 'kp_divide', 'thinspace', 'zerosuperior', 'macedonia_kje',
    'cyrillic_el', 'xf86switch_vt_10', 'at', 'bar', 'kp_delete', 'sinh_u',
    'sunagain', 'downtack', 'arabic_question_mark', 'xf86documents',
    'function', 'kana_comma', 'sinh_gha', 'umacron', 'cyrillic_je',
    'xf86officehome', 'greek_lambda', 'sacute', 'hebrew_waw', 'hiragana',
    'dead_acute', 'ukrainian_ghe_with_upturn', 'xf86scrollup',
    'armenian_apostrophe', 'f5', 'greek_lamda', 'kp_3', 'hebrew_lamed',
    'xf86mycomputer', 'sinh_oo2', 'eisu_shift', 'kana_conjunctive',
    'xf86touchpadon', 'xf86_ungrab', 'sinh_pa', 'endash', 'nobreakspace',
    'xf86stop', 'sinh_sha', 'omacron', 'foursuperior', 'xf86poweroff',
    'hebrew_finalzade', 'permille', 'kana_ka', 'armenian_zhe', 'eacute',
    'braille_dot_4', 'hebrew_finalpe', 'georgian_ghan', 'igrave', 'kana_mi',
    'xf86calendar', 'kp_f4', 'insert', 'kana_ma', 'kana_mu', 'xf86dos',
    'thai_saraae', 'kp_separator', 'kana_a', 'upstile', 'f30', 'greek_theta',
    'georgian_khar', 'cyrillic_be', 'o', 'sinh_a', 'tcedilla', 'georgian_un',
    'xf86switch_vt_4', 'arabic_tcheh', 'greek_omicron', 'aplinedel',
    'cyrillic_em', 'xf86backforward', 'georgian_shin', 'tab', 'xf86news',
    'georgian_chin', 'arabic_kasratan', 'schwa', 'xf86audiomute', 'sinh_ga',
    'cyrillic_es', 'xf86back', 'thai_baht', 'xf86reload', 'sinh_ddha',
    'georgian_hie', 'itilde', 'sinh_jha', 'thai_chochang', 'farsi_0',
    'xf86menukb', 'xf86_prev_vmode', 'sinh_au', 'sinh_aee', 'iso_level3_lock',
    'delete', 'kana_n', 'heart', 'kp_1', 'xf86bluetooth', 'sinh_dha',
    'greek_finalsmallsigma', 'topt', 'up', 'armenian_ligature_ew',
    'xf86todolist', 'periodcentered', 'onesixth', 'armenian_ra', 'home',
    'braille_dot_9', 'xf86launch7', 'sabovedot', 'xf86audiomicmute',
    'cyrillic_ka_vertstroke', 'georgian_can', 'femalesymbol', 'kp_right',
    'thai_thothahan', 'armenian_da', 'xf86audiorewind', 'kana_ni', 'l2',
    'xf86audioplay', 'cyrillic_i', 'quoteright', 'super_l', 'partialderivate',
    'ooblique', 'armenian_tyun', 'hpinsertline', 'georgian_qar', 'fiveeighths',
    'arabic_hamza_above', 'amacron', 'babovedot', 'none', 'return', 'group1',
    'icircumflex', 'xf86away', 'seenkeyinsaxlayout', 'guilsinglright',
    'oacute', 'diamond', 'doublequote', 'arabic_5', 'arabic_dal', 'leftcaret',
    'doublelowquotemark', 'paragraph', 'asciitilde', 'xf86book', 'touroku',
    'downstile', 'kana_ke', 'questiondown', 'armenian_re', 'iacute', 'ssharp',
    'dead_macron', 'xf86audiomedia', 'f3', 'greek_pi', 'exclam', 'greek_iota',
    'cyrillic_nje', 'arabic_theh', 'cyrillic_en', 'numerosign', 'thai_saraaa',
    'sevensuperior', 'fabovedot', 'cyrillic_ya', 'dead_greek', 'greek_alpha',
    'wacute', 'oe', 'thai_sorusi', 'cancel', 'xf86addfavorite', 'xf86webcam',
    'sinh_o', 'numbersign', 'kanji', 'xf86_next_vmode', 'cyrillic_ef', 'f34',
    'thai_nonen', 'quote', 'macedonia_gje', 'xf86scrolldown', 'ccircumflex',
    'iso_next_group', 'arabic_sukun', 'kp_prior', 'tabovedot', 'greek_phi',
    'enfilledcircbullet', 'similarequal', 'thai_dochada',
    'xf86audiolowervolume', 'dead_belowring', 'idotless', 'xf86messenger',
    'braceright', 'kana_ta', 'squareroot', 'arabic_noon', 'xf86favorites',
    'thai_maihanakat', 'notelementof', 'xf86audionext', 'end', 'kana_nu',
    'seebkeyinsaxlayout', 'xf86monbrightnessdown', 'f11', 'sinh_va', 'kana_me',
    'hyper_l', 'xf86www', 'uring', 'armenian_tsa', 'rightanglebracket',
    'sinh_ng2', 'zacute', 'xf86start', 'hebrew_ayin', 'arabic_waw', 'aring',
    'arabic_ra', 'dead_tilde', 'xf86paste', 'sinh_cha', 'cyrillic_u',
    'thai_sarao', 'kana_sa', 'arabic_superscript_alef', 'dead_belowbreve',
    'hpclearline', 'kana_middledot', 'hebrew_zain', 'quoteleft', 'kra',
    'arabic_ha', 'thai_lochula', 'f2', 'sinh_sa', 'armenian_dza', 'kp_f2',
    'escape', 'cyrillic_ghe_bar', 'georgian_par', 'arabic_yeh', 'sinh_ma',
    'thai_khokhwai', 'georgian_we', 'zerosubscript', 'kana_e', 'sinh_ruu2',
    'greek_rho', '6', 'thai_thonangmontho', 'xf86zoomin',
    'byelorussian_shortu', 'elementof', 'kp_up', 'georgian_ban',
    'horizconnector', 'seenkey', 'arabic_dammatan', 'kp_equal', 'emptyset',
    'thai_leksi', 'thai_wowaen', 'xf86travel', 'arabic_alefmaksura',
    'aogonekl', 'xf86audiopause', 'dead_hook', 'ae', 'arabic_madonalef',
    'sinh_nga', 'arabic_khah', 'arabic_madda_above', 'kana_ha',
    'arabic_hamzaunderalef', 'iso_level3_latch', 'atilde', 'diaeresis',
    'greaterthanequal', 'farsi_9', 'xf86cd', 'xf86explorer', 'hebrew_dalet',
    'sunfa_diaeresis', 'f29', 'xf86itouch', 'sinh_nna', 'arabic_qaf',
    'sinh_thha', 'kana_fu', 'dollar', 'fivesuperior', 'arabic_seen', 'radical',
    'thai_maitaikhu', 'georgian_jil', 'ogonek', 'execute', 'greek_epsilon',
    'ucircumflex', 'identical', 'sinh_i', 'xf86rotationkb', 'rightcaret',
    'arabic_tatweel', 'l1', 'i', 'hebrew_finalmem', 'x', 'armenian_full_stop',
    'uhorn', 'armenian_exclam', 'sinh_ee2', 'eisu_toggle', 'onehalf',
    'xf86userpb', 'm', 'thai_sosala', 'sinh_kunddaliya', 'arabic_shadda',
    'scroll_lock', 'sinh_ya', 'xf86music', 'thai_chochoe', 'xf86video',
    'hpsystem', 'arabic_tehmarbuta', 'tcaron', 'logicaland', 'undo', 'sinh_ee',
    'arabic_fatha', 'xf86xfer', 'question_mark', 'arabic_gaf', 'sinh_nja',
    'xf86word', 'dead_dasia', 'twosuperior', 'xf86switch_vt_6', 'thai_chochan',
    'f4', 'hpinsertchar', 'rightarrow', 'cyrillic_u_straight_bar', 'any',
    'kana_closingbracket', 'jcircumflex', 'thai_popla', 'dcaron', '9',
    'seconds', 'arabic_dad', 'nabla', 'kana_ro', 'thai_maiyamok',
    'cyrillic_tse', 'arabic_9', 'ecaron', 'thai_saraam', 'rightt',
    'georgian_hoe', 'xf86q', 'dead_comma', 'thai_maitho', 'massyo', 'sinh_au2',
    'kana_se', 'f16', 'partialderivative', 'kp_6', 'greek_eta', 'xf86homepage',
    'sinh_lu', 'therefore', 'lcaron', 'hebrew_resh', 'backslash', 'zcaron',
    'kp_down', 'ukrainian_ie', 'hebrew_chet', 'thai_yoying', 'yen',
    'parenleft', 'cyrillic_er', 'gbreve', 'armenian_ayb', 'armenian_lyun',
    'ograve', 'ukrainian_yi', 'armenian_za', 'thai_topatak', 'semivoicedsound',
    'ocircumflex', 'cyrillic_ie', 'sinh_ai', 'xf86launchc',
    'xf86monbrightnessup', 'cyrillic_shcha', 'trademark', 'k', 'xf86close',
    'henkan_mode', 'kana_ri', 'xf86audiopreset', 'thai_saraii', 'kana_so',
    'xf86launchf', 'threeeighths', 'seebkey', 'f35', 'xf86launcha', 'eogonek',
    'sunopen', 'xf86openurl', 'sunfront', 'f26', 'ecircumflex',
    'lowleftcorner', 'sinh_dda', 'yacute', 'iso_level5_latch', 'copyright',
    'arabic_kasra', 'thai_leknung', 'xf86shop', 'section', 'multiply',
    'cyrillic_ve', 'dead_iota', 'xf86rotationlocktoggle', 'thai_soso',
    'sinh_nya', 'cyrillic_ka_descender', 'ccaron', 'thorn', 'logicalor',
    'thai_thophuthao', 'armenian_se', 'kana_wa', 'georgian_in',
    'xf86switch_vt_3', 'sunstop', 'guillemotleft', 'sinh_tta', 'kana_ku',
    'cyrillic_dzhe', 'dead_belowdot', 'exclamdown', 'arabic_1',
    'sunaudiolowervolume', 'arabic_fullstop', 'upleftcorner', 'mu',
    'xf86suspend', 'trigraph_c_h', 'arabic_fathatan', 'dead_belowcircumflex',
    'kana_yu', 'kp_0', 'uogonek', 'georgian_cil', 'arabic_hamzaonyeh',
    'hangul', 'sinh_oo', 'sinh_ae', 'thai_paiyannoi', 'brokenbar',
    'xf86contrastadjust', 'kana_ne', 'farsi_8', 'leftsinglequotemark',
    'select', 'lacute', 'xf86wakeup', 'sinh_uu', 'thai_sarauee', 'digraph_ch',
    'minus', 'prior', 'sinh_ai2', 'onesubscript', 'arabic_2',
    'cyrillic_shorti', 'ncedilla', 'cyrillic_u_macron', 't', 'dead_diaeresis',
    'hcircumflex', 'georgian_san', 'dead_abovecomma', 'notequal', 'c', 'f6',
    'arabic_heh', 'voicedsound', 'cyrillic_ze', 'rcedilla', 'georgian_he',
    'f9', 'arabic_ddal', 'braille_dot_8', 'serbian_tshe', 'egrave',
    'cyrillic_schwa', 'arabic_comma', 'd', 'arabic_ghain', 'kana_mo',
    'imacron', 'sinh_ii2', 'hyper_r', 'thai_lekhok', 'bott', 'georgian_zhar',
    'xf86terminal', 'georgian_har', 'thai_rorua', 'underscore',
    'armenian_accent', 'w', 'thai_fofan', 'hstroke', 'cyrillic_ka',
    'arabic_rreh', 'armenian_to', 'ydiaeresis', 'farsi_yeh', 'greek_gamma',
    'f7', 'kana_no', '0', 'onequarter', 'thai_maichattawa', 'kana_lock',
    'eurosign', 'arabic_hah', 'greater', 'caps_lock', 'hebrew_bet',
    'odiaeresis', 'pabovedot', 'sinh_ba', 'control_r', 'b', 'braille_dot_10',
    'armenian_e', 'armenian_vo', 'control_l', 'doubleacute', 'xf86audioprev',
    'braille_dot_3', 'iso_level5_lock', 'kp_suptract', 'asciicircum', 'caret',
    'thai_loling', 'cyrillic_zhe', 'greek_psi', 'emdash', 'kana_u',
    'idiaeresis', 'xf86user1kb', 'dead_ogonek', 'slash', 'xf86launch3',
    'dagger', 'l6', 'f17', 'xf86forward', 'xf86scrollclick', 'arabic_heh_goal',
    'kana_ru', 'arabic_zah', 'thai_sarae', 's', 'xf86launch0', 'greek_beta',
    'sinh_ca', 'iso_left_tab', 'kp_multiply', 'xf86monbrightnesscycle',
    'uparrow', 'thai_saraa', 'scedilla', 'sinh_ra', 'f22', 'meta_r',
    'greek_nu', 'thai_totao', 'malesymbol', 'arabic_yeh_baree', 'apostrophe',
    'ordfeminine', 'breve', 'l10', 'kana_ra', 'sinh_o2', 'thai_phophung',
    'sinh_bha', 'h', 'arabic_peh', 'xf86search', 'period', 'sinh_ri',
    'multi_key', 'aacute', 'xf86zoomout', 'armenian_sha', 'cyrillic_e',
    'xf86history', 'thai_thothong', 'dead_belowcomma', 'greek_kappa', 'leftt',
    'oneeighth', 'acute', 'xf86go', 'hyphen', 'agrave', 'armenian_ini',
    'xf86eject', 'arabic_hamzaonwaw', 'iogonek', 'hebrew_pe', 'thai_ru',
    'ukrainin_ie', 'georgian_tan', 'thai_sarau', 'ncaron', 'tslash',
    'greek_zeta', 'kp_enter', 'iabovedot', 'kana_openingbracket', 'sinh_ndda',
    'arabic_sheen', 'xf86_cleargrab', 'georgian_nar', 'degree', 'cyrillic_ha',
    'xf86taskpane', 'thai_oang', 'f18', 'sunvideoraisebrightness', 'club',
    'greek_omega', 'kana_tsu', 'linefeed', 'dead_circumflex', 'thai_khokhon',
    'f20', 'sunaudiomute', 'shift_lock', 'euros', 'eabovedot', 'division',
    'num_lock', 'kana_ya', 'n', 'cedilla', 'xf86launch8', 'arabic_thal',
    'parenright', 'ugrave', 'xf86wlan', 'thai_leksong',
    'armenian_separation_mark', 'underbar', 'thai_kokai', 'thai_khokhuat',
    'thai_thothung', 'ntilde', 'adiaeresis', 'arabic_tah', 'kp_begin',
    'georgian_zen', 'kp_decimal', 'arabic_noon_ghunna', 'cabovedot',
    'gcircumflex', 'farsi_3', 'eng', 'f8', 'vertbar', 'sinh_ha', 'break',
    'suncut', 'gabovedot', 'xf86audioraisevolume', 'acircumflex', 'f15',
    'xf86phone', 'gcaron', 'kana_hi', 'kp_home', 'cyrillic_i_macron',
    'thai_yoyak', 'arabic_damma', 'dead_doublegrave', 'georgian_fi',
    'thai_maiek', 'armenian_yech', 'arabic_hamza_below', 'thai_phosamphao',
    'hebrew_taw', 'arabic_8', 'cyrillic_io', 'doubledagger', 'registered',
    'xf86mail', 'xf86screensaver', 'comma', 'sinh_h2', 'arabic_jeh',
    'kana_chi', 'hpdeleteline', 'dead_invertedbreve', 'georgian_vin', 'f1',
    'thai_hohip', 'super_r', 'xf86switch_vt_9', 'sinh_i2', 'onethird', '3',
    'union', 'kana_wo', 'newsheqelsign', 'bracketleft', 'sunfind',
    'thai_bobaimai', 'f28', 'cyrillic_en_descender', 'kana_su', 'f33',
    'guillemotright', 'farsi_5', 'xf86ungrab', 'right', 'macron',
    'rightdoublequotemark', 'sinh_ae2', 'cyrillic_ghe', 'leftradical',
    'threesuperior', 'sinh_u2', 'xf86switch_vt_5', 'cyrillic_sha',
    'thai_lekkao', 'cacute', 'cyrillic_che_descender', 'georgian_las',
    'xf86switch_vt_12', 'hebrew_mem', 'f19', 'armenian_men', 'kcedilla',
    'print', 'sunprops', 'notsign', 'thai_sarai', 'threesubscript',
    'arabic_maddaonalef', 'l5', 'xf86kbdlightonoff', 'left', 'armenian_khe',
    'kp_subtract', 'arabic_tteh', 'arabic_zain', 'arabic_veh', 'xf86launch5',
    'hebrew_finalnun', 'armenian_gim', 'thai_lakkhangyao', 'f12', 'f14',
    'sinh_tha', 'zenkaku_hankaku', 'f31', 'kp_f3', 'kana_shi', 'y',
    'greek_horizbar', 'sinh_rii', 'xf86audioforward', 'xf86save',
    'hebrew_kaph', 'sinh_ja', 'sinh_lu2', 'serbian_dje', 'r', 'xf86launch2',
    'mabovedot', 'arabic_4', 'greek_xi', 'armenian_fe', 'voidsymbol',
    'xf86modelock', 'thai_thanthakhat', 'thai_saraue', 'thai_saraaimaimuan',
    'sinh_dhha', 'emacron', 'dead_breve', 'armenian_ho', '2', 'xf86fullscreen',
    'pause', 'georgian_char', 'xf86keyboard', 'arabic_ain', 'arabic_keheh',
    'horizlinescan5', 'scircumflex', 'sinh_ttha', 'xf86hotlinks', 'f23',
    'sinh_luu', 'georgian_hae', 'kana_ho', 'arabic_jeem',
    'xf86kbdbrightnessup', 'thai_nonu', 'kp_8', 'dabovedot',
    'cyrillic_u_straight', 'kp_insert', 'armenian_ke', 'j', 'armenian_o',
    'thai_moma', 'armenian_ken', 'leftarrow', 'iso_group_latch',
    'kana_fullstop', 'cyrillic_softsign', 'xf86launche', 'kp_next',
    'variation', 'xf86game', 'katakana', 'farsi_1', 'xf86battery',
    'intersection', 'georgian_kan', 'romaji', 'dead_cedilla', 'armenian_ghat',
    'approximate', 'thai_lekha', 'xf86open', 'dstroke', 'xf86standby',
    'thai_fofa', 'cyrillic_yeru', 'thai_lekpaet', 'kana_to'
}
